# Generated by Django 4.1.2 on 2023-02-24 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filturmapp', '0003_mainfilturm'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EmpLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appdate', models.DateField()),
                ('appname', models.CharField(max_length=250)),
                ('leavetype', models.CharField(max_length=250)),
                ('datefrom', models.DateField()),
                ('dateto', models.DateField()),
                ('resumeon', models.DateField()),
                ('leaveday', models.CharField(max_length=50)),
                ('leavebalance', models.CharField(max_length=50)),
                ('leavereason', models.CharField(max_length=50)),
                ('empl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filturmapp.mainfilturm')),
            ],
        ),
    ]
